version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: machine-repair-backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/machine-repair
      - JWT_SECRET=your_jwt_secret_key_here
      - PORT=5000
    ports:
      - "0.0.0.0:5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: machine-repair-frontend
    ports:
      - "0.0.0.0:80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
